
theme = "gruvbox"

[editor]

line-number = "relative"


mouse = true


auto-format = true


auto-pairs = false

[editor.lsp]

display-messages = true


[editor.cursor-shape]

insert = "bar"

normal = "block"


select = "underline"

[editor.file-picker]

hidden = false
