
[language-server.texlab]
command = "texlab"

[language-server.texlab.config]
auxDirectory = "output"

[language-server.texlab.config.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.build]
forwardSearchAfter = false
onSave = true
executable = "tectonic"
args = [
	"-X",
	"compile",
	"%f",
	"--synctex",
	"--keep-logs",
	"--keep-intermediates",
	"--outdir=output",
	"-Zshell-escape",
]

[[language]]
name = "latex"
language-servers = ["texlab", "ltex"] # ltex provides some autocompletion/grammar suggestions
indent = { tab-width = 4, unit = "\t" }

